### ISSUE TITLE
firefox cookie路径default后面有一串随机字符，大佬修一下

### ISSUE THREAD

**Issue by ifconfig2333** [DeEpinGh0st/Browser-cookie-steal#1]
![图片](https://user-images.githubusercontent.com/43915014/82756971-0b089a80-9e10-11ea-9b17-8b5e4e4dbc90.png)

**Comment by DeEpinGh0st** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/43915014/82756971-0b089a80-9e10-11ea-9b17-8b5e4e4dbc90.png)

已更新
